"""User

Revision ID: cad24fdcf315
Revises: 346a3a6516b4
Create Date: 2022-10-04 17:17:15.084509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad24fdcf315'
down_revision = '346a3a6516b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
